# fly.toml app configuration file generated for gewoonboeken on 2025-07-27T03:57:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gewoonboeken'
primary_region = 'ams'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
